### ISSUE TITLE
Installing from scratch

### ISSUE THREAD

**Issue by G2-DomP** [vicenteg/mapr-pcapstream#10]
Hi,

Following your instructions, I was getting the following build error:

warn] Run 'evicted' to see detailed eviction warnings
[info] Compiling 3 Scala sources to /root/dom/mapr-pcapstream/target/scala-2.10/classes...
[info] 'compiler-interface' not yet compiled for Scala 2.10.5. Compiling...
[info]   Compilation completed in 9.77 s
[warn] Class org.joda.convert.FromString not found - continuing with a stub.
[warn] Class org.joda.convert.ToString not found - continuing with a stub.
[warn] Class org.joda.convert.FromString not found - continuing with a stub.
[warn] Class org.joda.convert.ToString not found - continuing with a stub.
[warn] Class org.joda.convert.ToString not found - continuing with a stub.
[warn] Class org.joda.convert.FromString not found - continuing with a stub.
[warn] Class org.joda.convert.ToString not found - continuing with a stub.
[warn] Class org.joda.convert.FromString not found - continuing with a stub.
[warn] Class org.joda.convert.FromString not found - continuing with a stub.
[warn] 9 warnings found
[info] Packaging /root/dom/mapr-pcapstream/target/scala-2.10/pcapstream_2.10-1.0.jar ...
[info] Done packaging.
[success] Total time: 158 s, completed 15-Nov-2016 10:46:11

Adding:

libraryDependencies += "org.joda" % "joda-convert" % "1.2"

to build.sh appears to resolve the issue.

However running mapr ./submit.sh produces the following error:

mapr ./submit.sh 
Error: Could not find or load main class ..submit.sh

Any ideas ? (new to mapr)

**Comment by vicenteg** [comment]
Hi, thanks for the fix on the build warnings. I'd welcome a pull request if you'd like to send one.

as for the submit command, you should not need to say "mapr submit.sh", just "submit.sh". The readme says 

```
sudo -u mapr ./submit.sh
```

Which will run the script as mapr, so if you're dropping the sudo, you can also drop the `-u mapr`.

**Comment by G2-DomP** [comment]
Thanks, lets say I was over thinking the problem!

Will do on the "pull request"
